### ISSUE TITLE
exporting sample (aerosonde) crashes crrcsim 

### ISSUE THREAD

**Issue by monkeypants** [TLmaK0/avl-crrcsim-editor#1]
I exported the samples/aerosond/aerosonde.crr to crrcsim, and the newly created aerosonde.xml seems to be toxic to crrcsim. I used latest avl-crrcsim-editor (downloaded today), with locally built AVL  that seems to work OK (recent sources; built to single precision on Ubuntu 14.04 using GNU Fortran 4.8.2) and the standard Ubuntu-packaged crrcsim (0.9.12).

After exporting to the file aerosonde.xml, I moved it to /usr/share/games/crrcsim/models/ and changed it's ownership/permissions to match the other files. Restarting crrcsim, "aerosonde" then appeared in my list of planes. When I highlighted it in the list of planes, in the place where I usually see a preview of the plane instead I saw an error message "cannot load geometry". If I ignore that and click "OK", the scenery goes black and the lower left message panel repeats "Error: aircraft outside windfield simulation". In the terminal where I started crrcsim, on STDERR it repeats "warning: used BSOD workaround". Saving the configuration and restarting crrcsim does not restore the scenery. Changing back to another model, saving configuration, then restarting does restore crrcsim to fully working again.

This is the contents of the exported aerosonde.xml

    <?xml version="1.0" encoding="UTF-8"?>
    <CRRCSim_airplane version="2">
       <description/>
       <aero units="1" version="1">
          <ref area="6.204E-5" chord="0.002113" span="0.02938" speed="30.0"/>
          <misc CG_arm="0.25" Alpha_0="-0.10717683" eta_loc="0.3" span_eff="0.95"/>
          <m Cm_0="-0.0" Cm_a="-2.362754" Cm_de="-0.04383" Cm_q="-31.235634"/>
          <lift CL_0="0.0" CL_CD0="0.0" CL_a="5.847715" CL_de="0.009347" CL_drop="0.1" CL_max="1.1" CL_min="-0.6" CL_q="12.258541"/>
          <drag CD_AIsq="0.01" CD_CLsq="0.01" CD_ELsq="0.0" CD_prof="0.0" CD_stall="-0.5" Uexp_CD="0.5"/>
          <Y CY_b="-0.313303" CY_da="5.09E-4" CY_dr="-0.005134" CY_p="-0.216322" CY_r="0.207097"/>
          <l Cl_b="-0.106645" Cl_da="0.001568" Cl_dr="6.0E-5" Cl_p="-0.633341" Cl_r="0.017232"/>
          <n Cn_b="0.092549" Cn_da="-8.9E-5" Cn_dr="0.001815" Cn_p="-0.002388" Cn_r="-0.068703"/>
       </aero>
       <config>
          <descr_short>new config</descr_short>
          <mass_inertia I_xx="0.0" I_xz="0.0" I_yy="0.0" I_zz="0.0" Mass="0.0" units="1" version="1"/>
          <power/>
          <sound>
             <sample dist_max="0" filename="sound.wav" maxvolume="0.0" pitchfactor="0.0" type="0" v_max="0" v_min="0"/>
          </sound>
       </config>
       <graphics model="Crossfire.ac" version="1">
          <descr_long>
             <en>Default description</en>
          </descr_long>
          <descr_short>
             <en>default</en>
          </descr_short>
       </graphics>
       <CG units="1" x="-0.0" y="0.0" z="-0.0"/>
       <wheels units="1" version="1"/>
    </CRRCSim_airplane>

**Comment by TLmaK0** [comment]
Thanks @monkeypants, I use aerosonde.crr to unit test avl-crrcsim-editor, but I don't remember if I use it with real crrcsim.

I will check and fix it, so It make sense that this sample files should work with crrcsim.
