### ISSUE TITLE
ant build errors

### ISSUE THREAD

**Issue by monkeypants** [TLmaK0/avl-crrcsim-editor#3]
In the first comment on #1, you mentioned unit testing so I thought I would try to run them myself. This is the same environment as that ticket, noting ` java -version` gave me:

    java version "1.7.0_55"
    Java(TM) SE Runtime Environment (build 1.7.0_55-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 24.55-b03, mixed mode)

After trying to install build dependencies (guesswork - I'm not a java guy):

    apt-get install ant
    apt-get install junit

This ran without errors:

    ant clean

and so did this:

    ant test-report

(no errors reported, `BUILD SUCESSFUL`).

However, when I try to simply build with `ant` I get:

    BUILD FAILED
    /home/chris/src/avl-crrcsim-editor/nbproject/build-impl.xml:527: The following error occurred while executing this line:
    /home/chris/src/avl-crrcsim-editor/nbproject/build-impl.xml:221: Compile failed; see the compiler error output for details.

The output of -do-compile was:

    -do-compile:
    [javac] Compiling 74 source files to /home/chris/src/avl-crrcsim-editor/build/classes
    [javac] /home/chris/src/avl-crrcsim-editor/src/com/abajar/crrcsimeditor/CRRCsimEditor.java:40: error: package org.jdesktop.application does not exist
    [javac] import org.jdesktop.application.Application;
    [javac]                                ^
    [javac] /home/chris/src/avl-crrcsim-editor/src/com/abajar/crrcsimeditor/CRRCsimEditor.java:41: error: package org.jdesktop.application does not exist
    [javac] import org.jdesktop.application.SingleFrameApplication;
    [javac]                                ^
    [javac] /home/chris/src/avl-crrcsim-editor/src/com/abajar/crrcsimeditor/CRRCsimEditor.java:46: error: cannot find symbol
    [javac] public class CRRCsimEditor extends SingleFrameApplication {
    [javac]                                    ^
    [javac]   symbol: class SingleFrameApplication
    [javac] /home/chris/src/avl-crrcsim-editor/src/com/abajar/crrcsimeditor/CRRCsimEditor.java:89: error: method does not override or implement a method from a supertype
    [javac]     @Override protected void startup() {
    [javac]     ^
    [javac] /home/chris/src/avl-crrcsim-editor/src/com/abajar/crrcsimeditor/CRRCsimEditor.java:158: error: cannot find symbol
    [javac]         return Application.getInstance(CRRCsimEditor.class);
    [javac]                ^
    [javac]   symbol:   variable Application
    [javac]   location: class CRRCsimEditor
    [javac] /home/chris/src/avl-crrcsim-editor/src/com/abajar/crrcsimeditor/CRRCsimEditor.java:166: error: cannot find symbol
    [javac]         launch(CRRCsimEditor.class, args);
    [javac]         ^
    [javac]   symbol:   method launch(Class<CRRCsimEditor>,String[])
    [javac]   location: class CRRCsimEditor
    [javac] /home/chris/src/avl-crrcsim-editor/src/com/abajar/crrcsimeditor/MainFrame.java:197: error: package org.jdesktop.application does not exist
    [javac]         org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.abajar.crrcsimeditor.CRRCsimEditor.class).getContext().getResourceMap(MainFrame.class);
    [javac]                                 ^
    [javac] /home/chris/src/avl-crrcsim-editor/src/com/abajar/crrcsimeditor/MainFrame.java:197: error: package org.jdesktop.application does not exist
    [javac]         org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.abajar.crrcsimeditor.CRRCsimEditor.class).getContext().getResourceMap(MainFrame.class);
    [javac]                                                                                    ^
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 8 errors

**Comment by TLmaK0** [comment]
These errors are because the appframework.jar and swing-worker.jar isn't in the class path. These are added automatically by neetbeans project. If you already use netbeans, right-click in the project and then in resolver dependencies, and try to find this dependencies in netbeans libraries.

**Comment by monkeypants** [comment]
I live in emacs/gnu screen/bash, so would like to be able to build from CLI or similar if possible. I tried copying the jars from the "latest" build package to lib/ in my source directory (no joy), and also installing the libappframework-java Ubuntu package and/or the libbetter-appframework-java packages and none of those things worked.

Will try in NetBeans tomorrow (downloading it and it's dependencies now).

**Comment by TLmaK0** [comment]
Ok, I will add dependency management with maven to fix this things in the future.

**Comment by TLmaK0** [comment]
I have moved to sbt build tool

**Comment by monkeypants** [comment]
OK, I have pulled the latest sources, and installed Scala and sbt. When I try to run sbt it complains:

    me@mycomputer:~/src/avl-crrcsim-editor(master)$ sbt
    Loading /usr/share/sbt/bin/sbt-launch-lib.bash
    [info] Loading project definition from /home/chris/src/avl-crrcsim-editor/project
    /home/me/src/avl-crrcsim-editor/build.sbt:9: error: not found: value enablePlugins
    enablePlugins(JavaAppPackaging)
    ^
    [error] Type error in expression
    Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

The first time it loaded a lot of stuff before hitting that error. Subsequently, it went strait to that error. What else do I need to install?

**Comment by TLmaK0** [comment]
JavaAppPackaging should be installed by sbt through the project/plugins.sbt addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.0.0-M5")

You can remove enablePlugins(JavaAppPackaging) line, it is only for release packaging.

Be sure you use the last version of sbt 0.13.7, check it with 

    sbt sbtVersion

If you have the correct sbt version try to remove ~/.sbt/0.13/plugins

Another way could be remove ~/.ivy2 folder.

There is some people having this kind of issues with sbt

**Comment by monkeypants** [comment]
My issue was sbt version < 0.13.7, after upgrading that and now it works (with original build.sbt).

I added a bit of documentation in pull request.
